#ifndef _BDROID_BUILDCFG_H
#define _BDROID_BUILDCFG_H

#define BTM_DEF_LOCAL_NAME   "Galaxy M51"

#define BLE_VND_INCLUDED   TRUE
#define MAX_ACL_CONNECTIONS   16
#define MAX_L2CAP_CHANNELS    32
#define GATT_MAX_PHY_CHANNEL  10

#define AVDT_NUM_SEPS 35

#define BTM_ESCO_TRANSPORT_UNIT_SIZE_PCM16

#endif
